title: Furballize Ragdolls Cattery 波波球布偶貓舍
name: Furballize Ragdolls Cattery 波波球布偶貓舍
description: 波波球布偶貓舍位於高雄，為 TICA/CFA 註冊合格貓舍。致力於繁育貼近國際品種標準的冠軍血統布偶貓。Furballize Ragdolls Cattery is located in Kaohsiung, Taiwan and is registered in TICA/CFA. We committed breeding toward the Ragdoll breed standard with champion lines.
author: https://tsoliangwu.com/
author_email: tsoliangwu0130@gmail.com

baseurl:
url: https://furballizeragdolls.github.io/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
syntax_highlighter: rouge
exclude: ['README.md']
permalink: pretty

plugins:
  - jekyll-sitemap
