title: Furballize Ragdolls Cattery 波波球布偶貓舍
name: Furballize Ragdolls Cattery 波波球布偶貓舍
description: 波波球布偶貓舍 (Furballize Ragdolls Cattery) 為 TICA/CFA 註冊合格貓舍。致力於繁育貼近國際品種標準的冠軍血統布偶貓。
author: https://tsoliangwu.com/
author_email: tsoliangwu0130@gmail.com

baseurl:
url: https://furballizeragdolls.github.io/

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
syntax_highlighter: rouge
exclude: ['README.md']
permalink: pretty

plugins:
  - jekyll-sitemap
