title: 波波球布偶貓舍 | Furballize Ragdolls Cattery
description: 波波球布偶貓舍位於台灣高雄，為 TICA/CFA 雙註冊優良貓舍與台灣政府許可之合格特寵業，致力於繁育健康並貼近國際品種標準的冠軍血統布偶貓。我們因喜愛而繁育，用心自美國、日本、韓國等海外國家進口擁有美麗藍瞳的大型布偶貓。波波球的每隻貓爸爸及貓媽媽經 HCM/PKD 基因檢測均為陰性，並提供小貓家長 18 個月 HCM/PKD 基因遺傳疾病保障。波波球希望與大家分享擁有布偶貓的生活與喜悅，並為經完整社會化的布偶幼貓們找一個合適的家。Furballize Ragdolls Cattery is located in Kaohsiung, Taiwan and is registered in TICA/CFA. We committed breeding toward the Ragdoll breed standard with champion lines.
author: https://tsoliangwu.com
lang: zh-Hans-TW
logo: /assets/img/site-image.png
image: /assets/img/site-image.png

baseurl:
url: https://furballizeragdolls.github.io

facebook:
  publisher: https://www.facebook.com/furballchubbymeow

twitter:
  card: summary

social:
  name: Furballize Ragdolls Cattery 波波球布偶貓舍
  links:
    - https://www.facebook.com/furballchubbymeow

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/site-image.png

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
syntax_highlighter: rouge
exclude: ['README.md']
permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
